### ISSUE TITLE
Environment variables are inaccessible

### ISSUE THREAD

**Issue by tylers-username** [meanbee/docker-magento#55]
I may be misunderstanding how the containers should be launched. My assumption is that since we have a docker-compose.yml that `docker-compose up` or `docker-compose up --build` will make the CLI services AWS environment variables available. However, executing `docker exec $(docker ps | grep cli | cut -d ' ' -f 1) printenv` shows that the AWS variables were not set.

Should the cli service be launched with `docker-compose run ...`?

**Comment by tgerulaitis** [comment]
Yes, `cli` is meant for one-off runs. It is defined in `docker-compose.yml` as a service, because Docker Compose does not allow for ad-hoc services, so when launched with `docker-compose up`, it will simply exit.

To run one of the cli commands, you have to use `docker-compose run`, e.g.:
```
docker-compose run --rm cli magerun cache:flush
```

However, all of the environment variables that you have defined in `docker-compose.yml`, such as the AWS credentials, will still be available.

**Comment by tylers-username** [comment]
I was many unnecessary commands to make this container setup work. Thanks to your clarification, they're no longer needed.
