### ISSUE TITLE
Response is quite slow on Ubuntu 17

### ISSUE THREAD

**Issue by tylers-username** [meanbee/docker-magento#56]
- Host: 15 GB memory
- Host: Intel® Core™ i5-7440HQ CPU @ 2.80GHz × 4
- Host: Ubuntu 17.04
- Docker version 17.06.0-ce, build 02c1d87
- docker-compose version 1.13.0, build 1719ceb
- Magento: 1.14.3.3
- Products: 2,600
- Stores: 2
- `/etc/hosts`
   
   ```
   127.0.0.1       localhost
   127.0.1.1       tyler-Precision-5520
   
   # The following lines are desirable for IPv6 capable hosts
   ::1     ip6-localhost ip6-loopback
   fe00::0 ip6-localnet
   ff00::0 ip6-mcastprefix
   ff02::1 ip6-allnodes
   ff02::2 ip6-allrouters

   #Container
   172.19.0.2 stage.domain.com
   172.19.0.3 mysql.stage.domain.com
   ```

**Comment by tgerulaitis** [comment]
@tylerssn We run 16.04 LTS for our staging environments and have not experienced any systematic slowness. We have seen some Magento stores be quite inconsistent and sometimes slow down to a crawl, but never spent enough time to figure out why that happens. The container performance is not good enough for us to trust it for production, but it seems good enough for staging QA.

What cache is your store using? Is the source code mounted into a volume or stored in the container?

**Comment by tylers-username** [comment]
I'm using file storage and the volume is mounted.

**Comment by tgerulaitis** [comment]
Hmm, I'm not sure how having file cache in a mounted volume affects performance on Ubuntu (it certainly does on OS X and Windows, but the setup there is more complicated), so this might be a red herring, but I'd try switching to database cache (or, even better, Redis) and see if it improves things at all.

If that doesn't help, then maybe the only option is to enable the Profiler in Magento and trying to pinpoint where the time is spent generating a response.

**Comment by tylers-username** [comment]
To be sure that we're talking about the same thing when saying the volume is mounted, I am using:

      appdata:
        image: tianon/true
        volumes:
          - .:/var/www/html

I enabled redis cache, and it did help a little. What I am noticing is that when block and full page cache is disabled, `docker stats` is showing CPU usage spiking to 100%+ for the web container.

**Comment by tgerulaitis** [comment]
Yeah, we're on the same page about mounted volumes.

I've seen containers spiking in CPU when cache is disabled once or twice before, mostly on M2, because cache plays an even bigger role there. I don't really know what to suggest, though, other than keeping the cache on.

**Comment by gety9** [comment]
@tgerulaitis 

> We run 16.04 LTS for our staging environments and have not experienced any systematic slowness. We have seen some Magento stores be quite inconsistent and sometimes slow down to a crawl, but never spent enough time to figure out why that happens. The container performance is not good enough for us to trust it for production, but it seems good enough for staging QA.

Tomas, i know it's an old post, but are you still against using docker for production? We are using your image for local and staging, and now considering trying it for production, but not sure if we should do it.

**Comment by tgerulaitis** [comment]
@gety9,

I like the idea of Docker in production, but we've just not battle tested them enough in production-like conditions (i.e. with production levels of simultaneous requests and orders being placed), so I don't have complete trust in our images. Have you done any kind of performance testing on your environments?

**Comment by gety9** [comment]
@tgerulaitis 

>I like the idea of Docker in production, but we've just not battle tested them enough in production-like conditions (i.e. with production levels of simultaneous requests and orders being placed), so I don't have complete trust in our images. Have you done any kind of performance testing on your environments?

hadn't done any tests yet, apart from using your images on staging and having zero issues.

What tests would you recommend to do, and should be any changes made to images to make them more production ready?

**Comment by tgerulaitis** [comment]
@gety9,

My main focus would be load testing. I'd get some visitor numbers and conversion rates from GA and configure some load tests: one with regular visitors/conversions, one with sale values, one with black friday, and maybe one with 1.5x numbers of the highest one of the previous ones for "what if suddenly everyone wants to buy from us" scenario. See how the environment fares with the different levels of load - if you're happy with the performance, then it should be good to go!

I've used https://www.blazemeter.com/ before, when doing this kind of testing for client production environments, but there are several alternatives.

In terms of settings, nothing comes to mind immediately, other than maybe `memory_limit` in php, but please do a review of PHP ini settings and MySQL config. There are a bunch of guides out there for production ready settings - we've not focused on production for these images so I'm sure there's going to be one or two to tweak to get extra performance.

**Comment by gety9** [comment]
@tgerulaitis thank you! appreciate your suggestions!

**Comment by gety9** [comment]
@tgerulaitis 

I was advised that DB should not be in docker for production. And when doing google search came to [similar suggestions](https://www.reddit.com/r/docker/comments/asbl4t/database_in_docker_container_vs_remote_managed/):

> I'll only use docker contained db's for development. When it comes to production I'll get something more permanent and managed either by me or a service. Redis or memcache in a docker is fine for all facets too though! I don't see enough added benefit of running containers for db yet in production.

What's your opinion on that?

**Comment by tgerulaitis** [comment]
@gety9 ,

I think it depends on your situation, but in general I think I'd agree.

In production, the database is the only thing you really don't want to lose, because that's where all of your customer data lives. So you'll want some kind of recovery and replication set up, with hard backups on a schedule. All of this is achievable in Docker, but Docker is kind of an additional nuisance on top.

If you are hosting with a provider that has DB as a service (like AWS or similar) - I would look into that (as always, it's a cost vs benefit balance). Having your data automatically managed, with resilience, backups and recovery, is one less headache for you to worry about.

If you do end up with managing a database yourself, the difference between Docker over native in terms of benefits in production is small:

With Docker, mysql is still a process running on the host machine, but it's isolated (unable to access the full machine) and is controlled by the Docker daemon (enforcing limits and costing a small performance overhead). You can easily manage your DB dependencies, by pulling a Docker image, and replace your DB in place if something goes wrong (by booting up an additional container and swapping connection details).

With native, mysql is controlled directly by the host machine kernel and has full access to the system and available resources. However, you will have to manage the dependencies yourself (ensure that packages are installed on the host) and it's not as easy to hot swap the database.

It's not a hard yes/no situation, but I do see the argument. In production, the db is the only container you don't want to suddenly disappear and be recreated, without making sure that the data is persisted first. So it's easier to just avoid containers and have it running as a service. Plus, it makes it easier to hook up other reliability services to it as you don't have to negotiate with Docker. And in an ideal world, you can just hand over the responsibility for your data to a 3rd party for a small fee and not worry about it at all.

**Comment by gety9** [comment]
@tgerulaitis 

Thank you Thomas, great points, makes total sense.

A little unrelated question, but what's your opinion on magento multi store? We are adding additional store, and will have 2 more later. So it will be 4 stores with 2 languages each.

So i am trying to decide should we do multi site on single magento instance or should we do separate magento installs ? Performance that's my main concern.

**Comment by tgerulaitis** [comment]
@gety9,

No worries!

Performance should be fine with 8 "store views". Most DB tables are either split by store, or indexed to help with quick lookups. The most I've used, I think, was 30 stores, but I've heard of people with hundreds of stores on their setup. I'm sure once you get to that level, you need every bit of optimisation you can get, but for a few stores I wouldn't worry about it.

The one thing I would consider is extensions and third party integrations. I've come across extensions in the past that only allow configuration on a global level and needed to patch modules when we only wanted them enabled for a particular store in a multi store setup (e.g. a popular faceted navigation module from a well known developer...). So I would do a quick review of the modules you have installed that you may not want to be enabled on the new stores. And the additional modules and integrations that you may want for the new stores.
