### ISSUE TITLE
Suggested Project Structure

### ISSUE THREAD

**Issue by gety9** [meanbee/docker-magento#64]
Guys hi,

It's not an issue but more a question on project structure you usually use.

Do you recommend to keep all files in project repo under git control(including core and all modules).
or do you separate core from main repo?

I was researching on ways to structure the project (currently we keep everything in main repo), and saw these suggestions/examples:
https://magento.stackexchange.com/a/72791/50995
https://magento.stackexchange.com/a/53330/50995
https://gist.github.com/ottonet/48ec65bdfeaf814f92af

But than on your coding standards page i saw these recommendation "Unless otherwise dictated by project standards, Magento extensions should always be installed fully and committed to the respository. Symlinks or composer dependencies should not be used."

So i wonder what is the right approach.

**Comment by tgerulaitis** [comment]
Hey,

I don't think there's a right or wrong approach to take when deciding whether to commit vendor files to your project repository. Both approaches have their advantages and disadvantages.

For Magento 1, we've been committing the entirety of Magento to our repositories since before Composer installing was an option. For M2, we've tried both approaches and I think we'll end up leaning towards committing `vendor/` too. Committing all of the files allows us to speed up build times and ensures that we can always deploy the project, even when third party services (like Composer, or Magento's repository) are having issues. The disadvantage is that we don't automatically get the latest versions of the packages installed when we build, but that means we can decide when we want to upgrade, and make sure that we test the upgrades when they happen.

But, like I said, either approach is valid, it just depends on what your personal preferences are.

T

**Comment by gety9** [comment]
@tgerulaitis 

Thomas, thank you for your reply.
Makes sense. One of the reasons that i was asking this is that we have a group of base modules (30 modules or so) that is same for 3 projects, so we are thinking of putting them in separate repo and include through composer.

One more question if you don't mind, in your development work flow do you use modman to separate modules from the core? Something like [this](https://www.kt-team.de/blog/composer-modman-n98magerunEN).
You have modman preinstalled on the images, so i suppose you are using it?

**Comment by tgerulaitis** [comment]
No worries, @gety9 ! Glad to share the knowledge.

Yeah, we use modman to install and update third party modules where possible, but once installed (with `modman deploy --copy`) we commit the module files.

T
