### ISSUE TITLE
Implement a solution for running the cron

### ISSUE THREAD

**Issue by punkstar** [meanbee/docker-magento#9]
We need to consider how we are going to run the cron in this environment.  I see three approaches:
- Add a `crontab` entry in the `apache` image that runs `cron.sh`
- Rely on the host machine to run a command like `docker-compose run tools bash /var/www/html/cron.sh` on a schedule
- Add a new cron image which runs the cron in the foreground (somehow!) which runs as a permanent service (in the `docker-compose` sense)

Thoughts?

**Comment by punkstar** [comment]
I don't really like 1) or 2) :smile:

**Comment by tgerulaitis** [comment]
I like having separate containers for web and cli and option 2) is not really "the docker way", so 3) sounds like the best solution.

**Comment by punkstar** [comment]
I agree.  Looks like this outlines the approach we need to take at: http://www.ekito.fr/people/run-a-cron-job-with-docker/

**Comment by tgerulaitis** [comment]
I attempted to create an image, based from the same templates as the php-cli images (except without debug), that would run cron in the foreground.

Things I've learned from attempting to write a cron image based on the same templates as the php-cli images:
1. You can not mount crontab entries. cron has very strict permissions for crontab files (owned by root, not writable by group), which causes problems when the files are mounted.
2. The www-data user doesn't seem to have access to php. When I attempted to run the cron as www-data (which we need, otherwise cron could create files that the web server would not be able to read), cron was never executed, because `which php` in the `cron.sh` file returns an empty string.

I don't have any more time to waste on this at the moment.
